#!/bin/bash

if [[ "$@" =~ "clean" ]]; then
    rm -rf *.abc *.ap *.ai *.an *.pa
    exit 0
fi

file_path=$1
file_name=$(basename "$file_path" | cut -d. -f1)

es2abc $file_path --merge-abc --module --type-extractor --output $file_name.abc

ark_js_vm --enable-pgo-profiler=true --compiler-pgo-profiler-path=$file_name.ap --entry-point=$file_name $file_name.abc

if [[ "$@" =~ "aot" ]]; then
    ark_aot_compiler --enable-pgo-profiler=true --compiler-pgo-profiler-path=$file_name.ap --aot-file=$file_name $file_name.abc
fi

if [[ "$@" =~ "asm" ]]; then
    ark_js_vm --entry-point=$file_name --aot-file=$file_name $file_name.abc
fi
