#!/bin/bash

check() {
    if [ $? -ne 0 ]; then
        echo "[Error] $1 command failed with exit code $?"
        exit 1
    fi
}

run() {
    echo -e "\e[96m$1\e[0m"
    $1
    check $1
}

if [[ "$@" =~ "clean" ]]; then
    rm -rf *.abc *.ap *.ai *.an *.pa *.abc.ll *.abc_opt.ll *.log
    exit 0
fi

if [ "$1" == "build" ]; then
    if [[ "$2" == "pre" ]]; then
        run "$OHOS_ROOT/build/prebuilts_download.sh"
    elif [[ "$2" == "debug" ]]; then
        run "$OHOS_ROOT/build.sh --product-name rk3568 --no-prebuilt-sdk --build-target ark_js_host_linux_tools_packages --build-target ets_frontend_build --build-target ark_js_packages --build-target ark_host_linux_tools_packages --gn-args is_debug=true"
    elif [[ "$2" == "ut" ]]; then
        if [[ -n "$2" ]]; then
            run "$OHOS_ROOT/build.sh --no-prebuilt-sdk --product-name rk3568 --build-target ${2}Action --gn-args is_debug=true"
        else
            run "$OHOS_ROOT/build.sh --no-prebuilt-sdk --product-name rk3568 --build-target ark_js_host_unittest --gn-args is_debug=true"
        fi
    elif [[ "$2" == "262aot" ]]; then
        cd $OHOS_ROOT/arkcompiler/ets_frontend
        if [ -n "$2" ]; then
            run "python3 $OHOS_ROOT/arkcompiler/ets_frontend/test262/run_test262.py --file $2 --es2021 all --libs-dir $OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_runtime:$OHOS_ROOT/out/rk3568/clang_x64/thirdparty/icu:$OHOS_ROOT/out/rk3568/clang_x64/thirdparty/zlib:$OHOS_ROOT/prebuilts/clang/ohos/linux-x86_64/llvm/lib --ark-frontend-binary=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_frontend/es2abc --ark-tool=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_runtime/ark_js_vm --ark-aot-tool=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_runtime/ark_aot_compiler --merge-abc-binary=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_frontend/merge_abc --ark-aot --ark-frontend=es2panda"
        else 
            run "python3 $OHOS_ROOT/arkcompiler/ets_frontend/test262/run_test262.py --es2021 all --libs-dir $OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_runtime:$OHOS_ROOT/out/rk3568/clang_x64/thirdparty/icu:$OHOS_ROOT/out/rk3568/clang_x64/thirdparty/zlib:$OHOS_ROOT/prebuilts/clang/ohos/linux-x86_64/llvm/lib --ark-frontend-binary=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_frontend/es2abc --ark-tool=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_runtime/ark_js_vm --ark-aot-tool=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_runtime/ark_aot_compiler --merge-abc-binary=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_frontend/merge_abc --ark-aot --ark-frontend=es2panda"
        fi
    elif [ "$2" == "262asm" ]; then
        cd $OHOS_ROOT/arkcompiler/ets_frontend
        if [ -n "$2" ]; then
            run "python3 $OHOS_ROOT/arkcompiler/ets_frontend/test262/run_test262.py --file $2 --es2021 all --libs-dir $OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_runtime:$OHOS_ROOT/out/rk3568/clang_x64/thirdparty/icu:$OHOS_ROOT/out/rk3568/clang_x64/thirdparty/zlib:$OHOS_ROOT/out/rk3568/clang_x64/thirdparty/cjson:$OHOS_ROOT/prebuilts/clang/ohos/linux-x86_64/llvm/lib --ark-tool=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_runtime/ark_js_vm --ark-frontend-binary=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_frontend/es2abc --merge-abc-binary=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_frontend/merge_abc --ark-frontend=es2panda"
        else
            run "python3 $OHOS_ROOT/arkcompiler/ets_frontend/test262/run_test262.py --es2021 all --libs-dir $OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_runtime:$OHOS_ROOT/out/rk3568/clang_x64/thirdparty/icu:$OHOS_ROOT/out/rk3568/clang_x64/thirdparty/zlib:$OHOS_ROOT/out/rk3568/clang_x64/thirdparty/cjson:$OHOS_ROOT/prebuilts/clang/ohos/linux-x86_64/llvm/lib --ark-tool=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_runtime/ark_js_vm --ark-frontend-binary=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_frontend/es2abc --merge-abc-binary=$OHOS_ROOT/out/rk3568/clang_x64/arkcompiler/ets_frontend/merge_abc --ark-frontend=es2panda"
        fi
    else
        run "$OHOS_ROOT/build.sh --product-name rk3568 --no-prebuilt-sdk --build-target ark_js_host_linux_tools_packages --build-target ets_frontend_build --build-target ark_js_packages --build-target ark_host_linux_tools_packages"
    fi
    exit 0
fi

file_path=$1
file_name=$(basename "$file_path" | cut -d. -f1)

if [[ "$@" =~ "abc" ]]; then
    run "es2abc $file_path --merge-abc --module --type-extractor --output $file_name.abc"
    run "ark_js_vm --enable-pgo-profiler=true --compiler-pgo-profiler-path=$file_name.ap --entry-point=$file_name $file_name.abc"
fi

for arg in "$@"; do
    if [[ "$arg" == "aot" ]]; then
        run "ark_aot_compiler --compiler-log=all0123 --log-level=warning --enable-pgo-profiler=true --compiler-pgo-profiler-path=$file_name.ap --aot-file=$file_name $file_name.abc"
    fi

    if [[ "$arg" == "asm" ]]; then
        run "ark_js_vm --compiler-log=all0123 --log-level=warning --entry-point=$file_name --aot-file=$file_name $file_name.abc"
    fi

    if [[ "$arg" == "dasm" ]]; then
        run "ark_disasm $file_name.abc $file_name.pa"
    fi
done
